### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by pedrofeliz90** [LyseonTech/dou-collector#6]
Olá, estou tentando instalar seu projeto, e estou recebendo o seguinte erro, sabe me informar qual o problema?

--------------

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#38
!!    #message: """
!!      Attempted to load class "Kernel" from namespace "App".\n
!!      Did you forget a "use" statement for "Symfony\Component\HttpKernel\Kernel"?
!!      """
!!    #code: 0
!!    #file: "C:\xampp\htdocs\symfony-project\bin\console"
!!    #line: 41
!!  }
!!  2020-10-05T08:32:31+02:00 [critical] Uncaught Error: Class 'App\Kernel' not found
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.

**Comment by vitormattos** [comment]
Atualizei o projeto recente, pode conferir novamente?

**Comment by pedrofeliz90** [comment]
Acredito que meu problema, é na instalação dos symfony... nunca havia usado o mesmo. = /

**Comment by vitormattos** [comment]
Recomendo utilizar em container, já está com o ambiente todo pronto para rodar a aplicação. Tem habilidade com docker? Executou o `composer install`?

**Comment by pedrofeliz90** [comment]
acredito que meu problema é no PHPUNIT, estou usando o xampp, e a versão php 7 e o phpunit 3.7, e não estou conseguindo atualizar o phpunit para a versão 9, já tentei de diversas formas.

**Comment by vitormattos** [comment]
Recomendo usar a PHP >= 7.3

**Comment by pedrofeliz90** [comment]
Olá, pois então, estou a usar o PHP >7.3, porém acredito que meu problema, é com PHPUNIT, veja a versão do seu, por favor.

**Comment by vitormattos** [comment]
As versões estão bloqueadas no composer.lock

No Packagist vem dizendo as versões de forma mais amigável:

https://packagist.org/packages/lyseontech/dou-collector

O PHPUnit é requistio para ambiente de desenvolvimento, apenas necessário se for fazer modificações no pacote.

Se instalar o projeto via composer não vai exigir PHPUnit.

**Comment by pedrofeliz90** [comment]
Minha dificuldade ta sendo rodar ele no XAMPP então, pois ele devolve um erro do PHPUNIT/Framework

**Comment by pedrofeliz90** [comment]
pelo que entendi, usando com composer, ele baixa o phpunit atualizado, porém, o sistema parece usar o o phpunit da raiz, que não é o atualizado, acredito ser isso o problema, porém não tenho certeza

**Comment by vitormattos** [comment]
Usando o composer vai instalar os pacotes descritos em require no `composer.json` que está na raiz do projeto.

Se der um git clone no projeto e instalar vai instalar a versão de desenvolvimento instalando o que está em require-dev a não ser que faça um `composer install --no-dev` e esteja tentando rodar direto do repo.

**Comment by pedrofeliz90** [comment]
to re-instalando meu XAMPP, já mexi tanto nele, que já nem deve prestar. kkkk.
Seguinte, sou um amante de programação, em especifico, php, mas sou apenas um entusiasta mesmo, na realidade sou advogado...
Vi esse seu projeto, e me ocorreu de fazer algumas alterações nele, para em vez de buscar licitações, buscar intimações de advogado.
Mas quanto o senhor cobraria em um sistema dessa forma, fazendo esse serviço, que eu mencionei, acredito, que seja basicamente o que esse seu sistema já faz.

Tem algum contato que consigo falar com o senhor, com mais facilidade? Discover? Skype? Telegram? Whatsapp?

**Comment by pedrofeliz90** [comment]
após, várias reinstalações, consegui rodar o sistema, obrigado

**Comment by pedrofeliz90** [comment]
Estou verificando o sistema, na realidade ele não lê o pdf né, apenas faz a pesquisa dentro do site in.gov.br, a principio pensei que ele fizesse leitura do pdf, eu queria fazer adaptação para o diario da justiça do meu estado Rondônia, porém, não faz pesquisa por palavra especifica, ou pelo menos não encontrei o API dele, apenas por data, gera o pdf, e tem que pesquisar dentro dele.

**Comment by vitormattos** [comment]
É, este coletor de dados é só para o DOU, não se aplica ao diário oficial de outros estados / municípios.

Está em nosso radar montar uma estrutura padrão para coleta de dados de licitações de outros lugares, inserir isto em banco de dados, ter alertas por palavras-chave mas nos falta o financiamento para avançar com o projeto.

**Comment by vitormattos** [comment]
Encerrando a issue por falta de iteração e por não terem sido identificados problemas no código.
